name: Build and Release winguake

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release 需要完整的 git 历史

      # If semantic-release decides to release, it will build package by running .prepare.ps1 in plugin @semantic-release/exec.
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # semantic-release 需额外安装的插件
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
